//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab2.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consolidated Edison
        ///Dana
        ///Jones Financial (Edward Jones)
        ///Abbott Laboratories
        ///Burlington Stores
        ///Masco
        ///Expeditors Intl. of Washington
        ///Pacific Life
        ///Insight Enterprises
        ///Loews
        ///Walt Disney
        ///Simon Property Group
        ///Charles Schwab
        ///IQVIA Holdings
        ///PREVIO
        ///Owens Corning
        ///American Electric Power
        ///Regeneron Pharmaceuticals
        ///CVS Health
        ///Progressive
        ///Allstate
        ///Marsh &amp; McLennan
        ///Beacon Roofing Supply
        ///NextEra Energy
        ///Molson Coors Brewing
        ///Lennar
        ///Freddie Mac
        ///Exxon Mobil
        ///Altice USA
        ///Applied Materials
        ///Robert Half [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompaniesNames {
            get {
                return ResourceManager.GetString("CompaniesNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nathalie
        ///Desiree
        ///Sofia
        ///Leah
        ///Camila
        ///Jessie
        ///Mariela
        ///Milagros
        ///Marlene
        ///Claire
        ///Shannon
        ///Skye
        ///Amirah
        ///Alma
        ///Chasity
        ///Eileen
        ///Jocelynn
        ///Gemma
        ///Esperanza
        ///Gillian
        ///Adriana
        ///Jordan
        ///Adeline
        ///Noelle
        ///Lorena
        ///Heaven
        ///Arely
        ///Carolyn
        ///Hillary
        ///Wendy
        ///Elisabeth
        ///June
        ///Annie
        ///Mylie
        ///Shyanne
        ///Charlize
        ///Keira
        ///Danika
        ///Melina
        ///Kira
        ///Adalyn
        ///Kathy
        ///Violet
        ///Naima
        ///Linda
        ///Lilly
        ///Marilyn
        ///Mareli
        ///Lisa
        ///Lindsey.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten #1
        ///Kindergarten #2
        ///Kindergarten #3
        ///Kindergarten #4
        ///Kindergarten #5
        ///Kindergarten #6
        ///Kindergarten #7
        ///Kindergarten #8
        ///Kindergarten #9
        ///Kindergarten #10
        ///Kindergarten #11
        ///Kindergarten #12
        ///Kindergarten #13
        ///Kindergarten #14
        ///Kindergarten #15
        ///Kindergarten #16
        ///Kindergarten #17
        ///Kindergarten #18
        ///Kindergarten #19
        ///Kindergarten #20
        ///Kindergarten #21
        ///Kindergarten #22
        ///Kindergarten #23
        ///Kindergarten #24
        ///Kindergarten #25
        ///Kindergarten #26
        ///Kindergarten #27
        ///Kindergarten #28
        ///Kindergarten #29        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Kindergartens {
            get {
                return ResourceManager.GetString("Kindergartens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martinez
        ///Pena
        ///Hart
        ///James
        ///Wells
        ///Spears
        ///Rodgers
        ///Hurley
        ///Case
        ///Ferguson
        ///Hickman
        ///Wilkins
        ///Schmidt
        ///Mooney
        ///Combs
        ///Gallagher
        ///Avery
        ///Davila
        ///Fowler
        ///Garrison
        ///Kline
        ///Norris
        ///Gentry
        ///Goodwin
        ///Munoz
        ///Buckley
        ///House
        ///Garyvio
        ///Santiago
        ///Dillon
        ///Solis
        ///Camacho
        ///Hester
        ///Mcfarland
        ///Beltran
        ///Cortez
        ///Saunders
        ///Savage
        ///Rollins
        ///Cardenas
        ///Garcia
        ///Marks
        ///Conway
        ///Farley
        ///Burke
        ///Wright
        ///Odom
        ///Bowman
        ///Flynn
        ///Cannon.
        /// </summary>
        internal static string LastNames {
            get {
                return ResourceManager.GetString("LastNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Braedon
        ///Shawn
        ///Chaz
        ///Lance
        ///Aiden
        ///Mekhi
        ///Lucian
        ///Collin
        ///Ivan
        ///Jaydon
        ///Frankie
        ///Elvis
        ///Darion
        ///Kash
        ///Kingston
        ///Jaydan
        ///Jamir
        ///Lewis
        ///Semaj
        ///Nikolas
        ///Kenneth
        ///Wayne
        ///Ellis
        ///Aarav
        ///Zack
        ///Reece
        ///Reuben
        ///Jamari
        ///Lawrence
        ///Ezra
        ///Valentino
        ///Jovan
        ///Jakobe
        ///Kody
        ///Harrison
        ///Arjun
        ///Marvin
        ///Rayan
        ///Case
        ///Luca
        ///Albert
        ///Thaddeus
        ///Chase
        ///Carlos
        ///Camren
        ///Remington
        ///Jason
        ///Ray
        ///Chance
        ///Mark.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School #1
        ///School #2
        ///School #3
        ///School #4
        ///School #5
        ///School #6
        ///School #7
        ///School #8
        ///School #9
        ///School #10
        ///School #11
        ///School #12
        ///School #13
        ///School #14
        ///School #15
        ///School #16
        ///School #17
        ///School #18
        ///School #19
        ///School #20
        ///School #21
        ///School #22
        ///School #23
        ///School #24
        ///School #25
        ///School #26
        ///School #27
        ///School #28
        ///School #29
        ///School #30
        ///School #31
        ///School #32
        ///School #33
        ///School #34
        ///School #35
        ///School #36
        ///School #37
        ///School #38
        ///School #39
        ///School #40
        ///School #41
        ///School #42
        ///School #43
        ///Schoo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Schools {
            get {
                return ResourceManager.GetString("Schools", resourceCulture);
            }
        }
    }
}
